version: '3.8'

services:
  mysql_read_db:
    image: mysql:latest
    container_name: mysql_read_db
    environment:
      MYSQL_ROOT_PASSWORD: root1
    volumes:
      - mysql_read_data:/var/lib/mysql
    ports:
      - "3306:3306"

  mysql_write_db:
    image: mysql:latest
    container_name: mysql_write_db
    environment:
      MYSQL_ROOT_PASSWORD: root2
    volumes:
      - mysql_write_data:/var/lib/mysql
    ports:
      - "3307:3306"
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
    ports:
      - "9092:9092"

volumes:
  mysql_read_data:
  mysql_write_data: